import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Service | simplifylegaldocument",
  description: "Read the terms and conditions for using the simplifylegaldocument platform.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen">
      <Navbar />
      <div className="pt-32 pb-24 max-w-4xl mx-auto px-6">
        <h1 className="text-5xl font-serif font-bold mb-8">Terms of Service</h1>
        
        <div className="prose prose-sm md:prose-base dark:prose-invert max-w-none">
          <p className="text-muted mb-8">Last updated: May 09, 2026</p>
          
          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
            <p>By accessing and using simplifylegaldocument (the "Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.</p>
          </section>
          
          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">2. Description of Service</h2>
            <p>Simplifylegaldocument provides an AI-powered tool that summarizes and explains legal documents. This Service is provided for informational and educational purposes only.</p>
          </section>
          
          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4 text-red-500">3. Not Legal Advice</h2>
            <p className="font-bold">IMPORTANT: Simplifylegaldocument is NOT a law firm and does not provide legal advice. Our summaries are generated by Artificial Intelligence and may contain errors or omissions.</p>
            <p className="mt-2">The use of our Service does not create an attorney-client relationship. You should always consult with a licensed attorney before signing any legal documents or making legal decisions.</p>
          </section>
          
          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">4. User Responsibilities</h2>
            <p>You are responsible for the documents you upload. You must have the right to upload and process these documents. You agree not to use the Service for any unlawful activities or to process highly sensitive/classified government documents.</p>
          </section>

          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">5. Intellectual Property</h2>
            <p>The code, design, and branding of simplifylegaldocument are the property of its owners. You may not copy, reverse engineer, or redistribute our platform without express permission.</p>
          </section>
          
          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">6. Limitation of Liability</h2>
            <p>Simplifylegaldocument and its operators shall not be liable for any damages arising from your use of the Service, including but not limited to direct, indirect, incidental, or consequential damages resulting from any errors in the AI-generated summaries.</p>
          </section>
          
          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">7. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Your continued use of the Service after changes are posted constitutes your acceptance of the new terms.</p>
          </section>
          
          <section className="mb-10">
            <h2 className="text-2xl font-bold mb-4">8. Contact</h2>
            <p>For questions regarding these terms, contact us at legal@simplifylegaldocument.com.</p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  );
}
