import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FAQ from "@/components/FAQ";

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen">
      <Navbar />
      <div className="pt-32 pb-24 max-w-4xl mx-auto px-6">
        {/* Existing content... */}
        <h1 className="text-4xl font-serif font-bold mb-8">Legal Disclaimer</h1>
        
        <div className="glass p-8 rounded-3xl space-y-6 text-muted leading-relaxed">
          <p className="font-bold text-text">Last Updated: May 2026</p>
          
          <p>
            The information provided on <span className="text-primary font-bold font-serif">simplify<span className="italic">legal</span>document</span> ("the Platform") is for general informational and educational purposes only. It is not, and is not intended to be, legal advice.
          </p>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-text">1. No Attorney-Client Relationship</h2>
            <p>
              Your use of the Platform, including the submission of documents for analysis or the use of AI-generated summaries, does not create an attorney-client relationship between you and simplify<span className="italic">legal</span>document or any of its employees, agents, or affiliates.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-text">2. AI Accuracy and Limitations</h2>
            <p>
              The summaries and analysis provided are generated by Artificial Intelligence (Google Gemini). While we strive for accuracy, AI can make mistakes, hallucinate details, or miss critical legal nuances. Legal documents are complex and context-dependent.
            </p>
            <p className="bg-risk-high/10 p-4 rounded-xl border border-risk-high/20 text-risk-high font-medium">
              NEVER SIGN A LEGAL DOCUMENT BASED SOLELY ON THE SUMMARY PROVIDED BY THIS PLATFORM.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-text">3. Seek Professional Counsel</h2>
            <p>
              We strongly recommend that you consult with a qualified attorney licensed in your jurisdiction before signing any legal agreement. Only a lawyer can provide advice tailored to your specific situation and ensure your rights are fully protected.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-bold text-text">4. Limitation of Liability</h2>
            <p>
              simplify<span className="italic">legal</span>document shall not be held liable for any damages, losses, or legal consequences arising from your reliance on the AI-generated content provided by this platform.
            </p>
          </section>
        </div>
      </div>

      <FAQ faqs={[
        {
          question: "Why is there a disclaimer on simplifylegaldocument?",
          answer: "The disclaimer is there to clarify that while our AI is powerful, it is not a lawyer. It's essential for users to understand the limits of AI-powered legal assistance."
        },
        {
          question: "Does simplifylegaldocument provide legal advice?",
          answer: "No. simplifylegaldocument provides information and document simplification, which is distinct from legal advice. Legal advice requires a professional relationship with a licensed attorney."
        },
        {
          question: "Should I rely solely on AI for my contracts?",
          answer: "No. You should use simplifylegaldocument as a starting point to understand your documents, but always have a professional review any legally significant contracts before signing."
        },
        {
          question: "What if the AI makes a mistake?",
          answer: "AI can occasionally misinterpret text or miss nuances. This is why we emphasize that our tool is for informational purposes and should be verified."
        },
        {
          question: "Is simplifylegaldocument responsible for my legal outcomes?",
          answer: "No, simplifylegaldocument and its creators are not responsible for any legal consequences or outcomes resulting from the use of the tool."
        }
      ]} />

      <Footer />
    </main>
  );
}
